version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          command: |
            TESTFILES=$(circleci tests glob "src/*.sh" | circleci tests split --split-by=timings)
            echo $TESTFILES
            bash $TESTFILES
workflows:
  version: 2
  test:
    jobs:
      - test